# --- !Ups

ALTER TABLE `language` ADD `created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `language` ADD `modified_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `city_i18n` ADD `created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `city_i18n` ADD `modified_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;